name: githuber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  flutter_heatmap_calendar: ^1.0.5
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  graphql_codegen: ^1.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
